### ISSUE TITLE
Class Level

### ISSUE THREAD

**Issue by skorobaeus** [Stegur/js-diploma#10]
https://github.com/Stegur/js-diploma/blob/3b82a900692475f148f2e5e8fc27210339a84d42/game.js#L146-L147

Лучше создать копии массивов и работать с ними, напр. `this.grid = field.slice();`

**Comment by Stegur** [comment]
Это для того чтобы при работе с ```this.grid``` не изменялись входящие аргументы?
Мы их вроди больше не используем...
Это правило для "входящих" массивов и объектов?

**Comment by skorobaeus** [comment]
Да, в этом коде мы больше их нигде не используем. Но изменение извне остаётся возможным, ведь в JS переменной присвается не сам массив, а ссылка на него; и несколько переменных могут ссылаться на один и тот же массив. Это не то что бы правило, но когда нет цели непосредственно изменить исходный массив, лучше себя обезопасить и снять копию.
