### ISSUE TITLE
removeActor

### ISSUE THREAD

**Issue by skorobaeus** [Stegur/js-diploma#11]
https://github.com/Stegur/js-diploma/blob/3b82a900692475f148f2e5e8fc27210339a84d42/game.js#L212

Значение переменной не меняется ==> лучше const

**Comment by Stegur** [comment]
Ага, понял. Смог провести параллель константы с использующимся методом. Есть еще какие-то комбинации, которые обязывают (рекомендуют) использовать сразу ```const```?

**Comment by skorobaeus** [comment]
Есть распространённое мнение, что вообще, по умолчанию, лучше всегда использовать именно const, а let использовать тогда, когда переменная точно будет изменяться.
