### ISSUE TITLE
handleObstacle()

### ISSUE THREAD

**Issue by skorobaeus** [Stegur/js-diploma#13]
https://github.com/Stegur/js-diploma/blob/3b82a900692475f148f2e5e8fc27210339a84d42/game.js#L378-L379

У нас в классе Вектор есть метод times, который, буквально, умножает координаты исходного вектора на любой необходимый множитель. Лучше в данном случае домножить на -1 с помощью метода times

**Comment by Stegur** [comment]
не сразу дошло что ```this.speed``` у нас экземпляр ```Vector```....
