### ISSUE TITLE
Класс Actor

### ISSUE THREAD

**Issue by skorobaeus** [Stegur/js-diploma#9]
https://github.com/Stegur/js-diploma/blob/3b82a900692475f148f2e5e8fc27210339a84d42/game.js#L39

Лучше не использовать конструктор Vector по умолчанию (`Vector()`), а передать нули (`Vector(0, 0)`). Если кто-то поменяет параметры по-умолчанию в конструкторе, всё сломается.

**Comment by Stegur** [comment]
Я так понимаю это касается параметров по-умолчанию именно у самого ```Vector?```

**Comment by skorobaeus** [comment]
Если я правильно поняла вопрос, то да. Т.е. мы не полагаемся на то, что код окажется неизменным. На большом проекте с несколькими разработчиками кто-то может поменять реализацию Vector и сделать значения по умолчанию (1, 1). А мы здесь об этом не знаем и продолжаем использовать Vector, полагаясь на то, что значения по умолчанию это (0, 0)
